name = input("შემოიტანეთ თქვენი სახელი: ")
surname = input("შემოიტანეთ თქვენი გვარი: ")
parent_name = input("შემოიტანეთ მშობლის სახელი: ")
parent_surname = input("შემოიტანეთ მშობლის გვარი: ")
favorite_color = input("შემოიტანეთ თქვენი საყვარელი ფერი: ")
favorite_car = input("შემოიტანეთ თქვენი საყვარელი მანქანა: ")
hobby1 = input("შემოიტანეთ თქვენი პირველი ჰობი: ")
hobby2 = input("შემოიტანეთ თქვენი მეორე ჰობი: ")
hobby3 = input("შემოიტანეთ თქვენი მესამე ჰობი: ")
print(f"მე ვარ {name} {surname}, ჩემი მშობლების სახელია {parent_name} {parent_surname}. ჩემი საყვარელი ფერია {favorite_color}, ჩემი საყვარელი მანქანაა {favorite_car}. ჩემი ჰობიებია: {hobby1}, {hobby2}, და {hobby3}.")
